

name: deploy
on:
  workflow_dispatch:
     inputs:
      update-version:
        type: boolean
        description: Update version
      version:
        description: "Version (x.x.x-suffix)"
        required: false
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Env
        run: |
          chmod +x "${GITHUB_WORKSPACE}/tools/vagrant/setup_ubuntu_18_04.sh"
          "${GITHUB_WORKSPACE}/tools/vagrant/setup_ubuntu_18_04.sh"
      - name: Deploy
        run: |
          "${GITHUB_WORKSPACE}/tools/distrib/distrib.sh" distrib_test
